server:
  port: 8089

spring:
  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://localhost:3306/pico_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username : root
    password : TIGER
  jwt:
    secret: govlepel@$&
  jpa :
    show-sql : true
    hibernate :
      ddl-auto : update
#      ddl-auto : create
    properties :
      hibernate :
        format_sql : true
    generate-ddl : true
    database : mysql
    database-patform : org.hibernate.dialect.MySQL8Dialect
  profiles:
    active: local
    devtools:
      livereload:
        enabled: true
      restart:
        enabled: false
      add-properties: false
  main:
    allow-bean-definition-overriding: true
  freemarker:
    cache: false
  thymeleaf :
    cache : false
    enabled : true
    prefix : classpath:/templates/
    suffix : .html

jwt:
  header: Autorization
  secret: UGxheURhdGEgRmluYWxQcm9qZWN0IFBJQ08gSldULVNlY3JldEtleQ0K7ZSM66CI7J20642w7J207YSwIOy1nOyihe2UhOuhnOygne2KuC0g7ZS87L2U
  token-validity-in-seconds: 86400
  #spring.profiles.include=oauth
